# Generated by Django 4.1.2 on 2022-10-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_remove_user_is_admin_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
                verbose_name="category",
            ),
            preserve_default=False,
        ),
    ]
