# Generated by Django 4.1.2 on 2022-10-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="publication_date",
            field=models.DateTimeField(auto_now=True, verbose_name="publication"),
        ),
    ]
